### ISSUE TITLE
Blocking jnn-pa.googleapis.com breaks Youtube on some videos

### ISSUE THREAD

**Issue by Yuki2718** [Kdroidwin/Kdroidwin-Tracking-Protection#1]
https://github.com/uBlockOrigin/uAssets/issues/20586#issuecomment-2275111776

**Comment by Kdroidwin** [comment]
削除しました。
他にもこのルールがあるフィルタはありますね。
https://rethinkdns.com/search?q=jnn-pa.googleapis.com
